name:                tomaru
version:             0.1.0.0
github:              "kmc-jp/tomaru"
license:             MIT
author:              "kmc-jp"
maintainer:          "hatsu@kmc.gr.jp"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kmc-jp/tomaru#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tomaru-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tomaru

tests:
  tomaru-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tomaru
